### PR TITLE
removed  memes.reverse()  and changed the code on line ( 60 )

### PR DESCRIPTION
**Pull request by Godwindaniel10**

### CODE REVIEW

**Comment by Godwindaniel10** [comment]
And also added an <html lang="en"> attributes to HTML pages

**Comment by shubhamcodez** [comment]
Done. Could you confirm if Load time got faster or not.

**Comment by Godwindaniel10** [comment]
Definitely!!!, load time got super faster...

**Comment by shubhamcodez** [comment]
> Definitely!!!, load time got super faster...

Cool. Congratulations. 👍🏻 
Would you like to work on any other issues or UI maybe?

**Comment by Godwindaniel10** [comment]
sure, i will love to work on any other issues or very much UI

**Pull request merged**
